version: '3.8'

services:
  # MySQL Database
  db:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: admin
      MYSQL_DATABASE: todo_app
      MYSQL_USER: todo_user
      MYSQL_PASSWORD: todo_password
    ports:
      - "3307:3306"
    volumes:
      - mysql_data:/var/lib/mysql
      - ./server/init-db.sql:/docker-entrypoint-initdb.d/init-db.sql

  # Backend API Server
  server:
    build: ./server
    environment:
      DB_HOST: db
      DB_USER: todo_user
      DB_PASSWORD: todo_password
      DB_NAME: todo_app
    ports:
      - "5000:5000"
    depends_on:
      - db

  # Frontend React App
  client:
    build: ./client
    ports:
      - "80:80"
    depends_on:
      - server

volumes:
  mysql_data: 